Tinkoff wrapper prototype
IdeaSeekers/Algotrading-backend pull request #3
Opened 2022-10-12 22:39 UTC by IdeaSeeker

## Пререквизиты

- В текущей версии все запросы идут к песочнице Тинькофф, так что можно делать безопасно всё, что угодно
- Сначала необходимо получить токен доступа к Тинькофф Инвестициям (нужен __Sandbox token__), подробнее об этом написано [тут](https://tinkoff.github.io/investAPI/token/)

### Основные классы

- `TinkoffActualAccount(token, accountId)` - делает все запросы к бирже (важно: боты должны взаимодействовать с ним только через механизм виртуальных аккаунтов, о чём написано ниже)
- `TinkoffVirtualAccountFactory(actualAccount)` - регистрирует сущности `TinkoffVirtualAccount` на основе переданного ему настоящего аккаунта. Позиции, которые доступны `actualAccount` будут разделены между создаваемыми виртуальными аккаунтами.
- `TinkoffVirtualAccount(actualAccount, availablePositions)` - виртуальный аккаунт, с которым взаимодействует конкретный бот. Имеет своё состояние (доступные деньги/акции/...). Нужен для того, чтобы разные боты, работая по сути через один `TinkoffActualAccount` не мешали другу другу (и вообще ничего не знали про остальных ботов).
- `TinkoffSandboxService(token)` - тестовый класс, нужен для того, чтобы создать аккаунт в песочнице и положить на него тестовые деньги. Аккаунт создается на 3 месяца, поэтому можно вызвать метод `createSandboxAccount()` этого класса, сохранить полученный `accountId` и потом пользоваться этим аккаунтом.

![image](https://user-images.githubusercontent.com/54814796/195455987-9e1ba542-ffbc-471b-9dbc-bf1764f73bbb.png)

### Пример

```Kotlin
val token = "<token>"
val accountId =  "<account-id>"

val account = TinkoffActualAccount(token, accountId)
val factory = TinkoffVirtualAccountFactory(account)

// Получаем текущую цену одной акции Яндекса
println(account.getLastPrice("BBG006L8G4H1"))

// Создаём виртуальный аккаунт и кладём на него 10к рублей
val virtualAccount = factory.openVirtualAccount(listOf(
    Currency("rub", Quotation(10000U, 0U))
)).getOrThrow()

// Можно класть не только рубли, если такие позиции есть на счёте `account`
val virtualAccountUsd = factory.openVirtualAccount(listOf(
    Currency("usd", Quotation(500U, 0U)),
    Security("BBG006L8G4H1", 1U)
))

// Выставляем заявку на покупку двух акций Яндекса по 17 рублей за шутку
// Заявка исполнится, когда на реальной бирже исполнится заявка с такой же ценой
val order = virtualAccount.postBuyOrder("BBG006L8G4H1", 2U, LimitedPrice.of(17U, 0U)).getOrThrow()

// Отменяем выставленную заявку
virtualAccount.cancelOrder(order.orderId)

// Выставляем заявку на покупку трёх акций Яндекса по рыночной цене
// Для песочницы заявка исполняется мгновенно
virtualAccount.postBuyOrder("BBG006L8G4H1", 3U, MarketPrice)

// Убеждаемся, что нам доступна купленная акция
println(virtualAccount.getPositions())
```

- При выставлении заявки на покупку акции, деньги списываются сразу, а сама акция приходит на счёт только после того, как заявка была исполнена на бирже.

- Чтобы узнать статус заявок можно вызвать методы `getOrderStatus(orderId)` или `getOpenOrders()`

2022-10-13 17:43 UTC, mandelshtamd approved these changes

2022-10-13 17:43 UTC, mandelshtamd commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/storage/SecurityStorage.kt
> +    // internal
а зачем комментарий?)

2022-10-13 17:43 UTC, mandelshtamd commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/storage/SecurityStorage.kt
> +                    securities.reduce { acc, security -> (acc + security)!! }
!!)

2022-10-13 17:43 UTC, mandelshtamd commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/storage/CurrencyStorage.kt
> +            error("Cannot increase CurrencyStorage by currency: $by")
кто-нибудь это ловит?

2022-10-13 17:43 UTC, mandelshtamd commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/model/TypeAliases.kt
> +typealias Figi = String
хорош

2022-10-13 17:43 UTC, mandelshtamd commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/model/Price.kt
> +sealed interface Price {
зачем sealed

2022-10-13 17:51 UTC, mandelshtamd commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/account/TinkoffActualAccount.kt
> +        if (lastPrices.size != 1) {
Насколько я понял, апишка предусматривает, что при getLastPrices обычно несколько цен приходит. Почему мы ошибку кидаем, когда 1?

2022-10-13 17:55 UTC, IdeaSeeker commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/storage/SecurityStorage.kt
> +    // internal
не знаю, так привык просто

2022-10-13 17:57 UTC, IdeaSeeker commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/storage/SecurityStorage.kt
> +                    securities.reduce { acc, security -> (acc + security)!! }
acc + security == null, если у них разный FIGI, значит после `.groupBy { it.figi }` всё будет точно ок

2022-10-13 17:58 UTC, IdeaSeeker commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/storage/CurrencyStorage.kt
> +            error("Cannot increase CurrencyStorage by currency: $by")
А я не знаю, как сделать лучше. Это по сути assert, то есть если ошибка кинется то всё, значит программа написана неверно. Лучше уж упасть, чем уйти в минус по деньгам, наверное...

2022-10-13 17:59 UTC, IdeaSeeker commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/model/Price.kt
> +sealed interface Price {
Чтобы when использовать без ветки else

2022-10-13 18:00 UTC, IdeaSeeker commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/account/TinkoffActualAccount.kt
> +        if (lastPrices.size != 1) {
Несколько цен приходит, если мы даём ему несколько цен. В данном случае я решил, что моя апишка будет позволять узнавать цену только одной бумаги. А значит и возвращать надо всегда что-то одно

2022-10-13 18:00 UTC, mandelshtamd requested changes

2022-10-13 18:00 UTC, mandelshtamd commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/error/Util.kt
> +        if (result.isSuccess)
а если success никогда не настанет?

2022-10-13 18:02 UTC, IdeaSeeker commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/account/TinkoffSandboxService.kt
> +            val moneyValue = Currency("RUB", Quotation(rubles, 0U)).toMoneyValue()
и не просто вынесу, а сделаю что-то централизованное, не только для рублей

2022-10-13 18:02 UTC, IdeaSeeker commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/account/TinkoffVirtualAccount.kt
> +            val executedOrderState = myOpenOrders[executedOrderId]!!
из строки выше очевидно, что `myOpenOrders` содержит нужный ключ

2022-10-13 18:03 UTC, IdeaSeeker commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/account/TinkoffVirtualAccount.kt
> +    // OrderState.BUY callbacks
В какой интерфейс

2022-10-13 18:03 UTC, IdeaSeeker commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/error/Util.kt
> +        if (result.isSuccess)
Значит вызывающий код зависнет

2022-10-13 18:05 UTC, IdeaSeeker commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/error/CannotOpenVirtualAccountError.kt
> +data class CannotOpenVirtualAccountError(
Давай уберу, да

2022-10-13 18:06 UTC, mandelshtamd commented on tinkoff-wrapper/src/main/kotlin/backend/tinkoff/account/TinkoffVirtualAccount.kt
> +    // OrderState.BUY callbacks
класс какой-то перегруженный получился как мне кажется, разбить бы на разных менеджеров хотя бы

2022-10-20 15:31 UTC, mandelshtamd approved these changes

2022-10-20 15:32 UTC, merged